### ISSUE TITLE
Generic Video Playback

### ISSUE THREAD

**Issue by frapit** [misc0110/pdf-webslides#3]
Would it be possible to support more generic video playback? I am embedding videos in my tex files using `\movie` command from the `multimedia` package coming with latex beamer. I think this is also the default way of pdfpc and they removed the support for their own `pdfpc-commands` package (see the updated example file https://github.com/pdfpc/pdfpc/blob/master/demo/pdfpc-video-example/video-example.tex). I am not sure how these packages differ in the resulting pdf but I can confirm that my videos are not recognized in pdf-webslides. Do you have some insight?

**Comment by misc0110** [comment]
I'll have a look at that.

**Comment by frapit** [comment]
Wow, thank you. That was fast. Now it woks great with my videos. I will close this. I also added some small functionality to position the videos at the correct place in the html, see the fork https://github.com/frapit/pdf-webslides. If you want to have this merged I can make a PR and clean up the snippet a bit. I will probably add some other functionalities like having multiple video annotations per page.

**Comment by misc0110** [comment]
That is great, I haven't had the time to look at all the details of the movie annotation. Would be great if you could make a PR.
